<a href="https://colab.research.google.com/github/HaileyHal/HCA-Project/blob/main/hca_combining_hurricanes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
hurricane = pd.read_excel('/content/cleaned_NEWhurricane_data.xlsx')
costly = pd.read_excel('/content/cleaned_mostcostlyhurricanedata.xlsx')

In [3]:
hurricane.head()

       name  year  month  day  category       date
0  AL022006  2006      7   19         0  2006/7/19
1  AL102004  2004      9   10         0  2004/9/10
2  AL121991  1991     11    2         1  1991/11/2
3  Al202011  2011      8   31         0  2011/8/31
4   Alberto  2000      8   13         3  2000/8/13

In [8]:
# making sure my column names match
costly.rename(columns={'City/Name':'name', 'Year':'year', 'Category':'category'}, inplace = True)
costly.head()

   Rank State             name  year  category  Deaths Other States
0     1    TX        Galveston  1900         4    8000          NaN
1     2    FL  Lake Okeechobee  1928         4    2500          NaN
2     3    LA         Katarina  2005         3    1200           MS
3     4   LA          Cheniere  1893         4    2000          NaN
4     5    SC      Sea Islands  1893         3    2000           GA

In [9]:
merged = hurricane.merge(costly, on = ['name', 'year', 'category'], how='left')
merged.head()

,name,year,month,day,category,date,Rank,State,Deaths,Other States
0,AL022006,2006,7,19,0,2006/7/19,NaN,NaN,NaN,NaN
1,AL102004,2004,9,10,0,2004/9/10,NaN,NaN,NaN,NaN
2,AL121991,1991,11,2,1,1991/11/2,NaN,NaN,NaN,NaN
3,Al202011,2011,8,31,0,2011/8/31,NaN,NaN,NaN,NaN
4,Alberto,2000,8,13,3,2000/8/13,NaN,NaN,NaN,NaN

In [11]:
merged['date'].value_counts()

date
2016/8/28     2
2020/9/17     2
1999/9/15     2
2008/10/16    2
2021/8/21     2
             ..
2016/8/24     1
2010/8/18     1
2018/9/6      1
1978/9/13     1
2020/10/28    1
Name: count, Length: 204, dtype: int64

In [13]:
# show all rows where date is 2016/8/28
merged[merged['date'] == '2020/9/17']

,name,year,month,day,category,date,Rank,State,Deaths,Other States
197,Teddy,2020,9,17,4,2020/9/17,NaN,NaN,NaN,NaN
207,Wilfred,2020,9,17,0,2020/9/17,NaN,NaN,NaN,NaN

In [ ]:
# NEW PROBLEM: This dataset includes hurricanes that hit the other side of the atlantic, not just the US side. I need to find a way to get all the names of the US hurricanes and filter by those somehow.